-- قاعدة البيانات المحدثة - عراق سيل
-- إضافة عمود reached_total (العدد الفعلي الذي وصل)

-- قم بنسخ هذا الكود وتشغيله في Supabase SQL Editor

-- 1) حذف الجداول الموجودة (إذا كانت موجودة)

DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.agents CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;

-- 2) إنشاء جدول المستخدمين

CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'supervisor', 'viewer')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 3) إنشاء جدول الوكلاء (مع عمود reached_total الجديد)

CREATE TABLE public.agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  note TEXT,
  contract_date DATE NOT NULL,
  phase TEXT NOT NULL CHECK (phase IN ('PHASE1','PHASE2','PHASE3','OLD')),
  site TEXT,
  fdt TEXT,
  board_name TEXT,
  phone TEXT,
  total_users INTEGER NOT NULL DEFAULT 0 CHECK (total_users >= 0),
  reached_total INTEGER NOT NULL DEFAULT 0 CHECK (reached_total >= 0),
  active INTEGER NOT NULL DEFAULT 0 CHECK (active >= 0),
  prev_active INTEGER NOT NULL DEFAULT 0 CHECK (prev_active >= 0),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 4) إنشاء جدول الفئات

CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  icon TEXT DEFAULT 'tv',
  color TEXT DEFAULT '#2196F3',
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 5) إضافة تريجر لتحديث updated_at

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- تريجر للمستخدمين
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- تريجر للوكلاء
CREATE TRIGGER update_agents_updated_at
    BEFORE UPDATE ON public.agents
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- 6) إضافة فهارس للأداء

CREATE INDEX idx_users_username ON public.users (username);
CREATE INDEX idx_users_role ON public.users (role);
CREATE INDEX idx_users_status ON public.users (status);
CREATE INDEX idx_agents_phase ON public.agents (phase);
CREATE INDEX idx_agents_contract_date ON public.agents (contract_date);
CREATE INDEX idx_agents_name ON public.agents (name);
CREATE INDEX idx_categories_sort_order ON public.categories (sort_order);

-- 7) تفعيل Row Level Security (RLS)

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 8) إضافة سياسات الأمان

-- سياسات المستخدمين
CREATE POLICY "Allow all operations on users" ON public.users
FOR ALL USING (true) WITH CHECK (true);

-- سياسات الوكلاء
CREATE POLICY "Allow all operations on agents" ON public.agents
FOR ALL USING (true) WITH CHECK (true);

-- سياسات الفئات
CREATE POLICY "Allow all operations on categories" ON public.categories
FOR ALL USING (true) WITH CHECK (true);

-- 9) إدراج المستخدمين التجريبيين

INSERT INTO public.users (username, full_name, password_hash, role, status) VALUES
('admin', 'مدير النظام', 'admin123', 'admin', 'active'),
('supervisor', 'مشرف النظام', 'sup123', 'supervisor', 'active'),
('viewer', 'مشاهد النظام', 'view123', 'viewer', 'active'),
('manager', 'مدير العمليات', 'mgr123', 'admin', 'active'),
('supervisor2', 'مشرف ثاني', 'sup456', 'supervisor', 'active');

-- 10) إدراج الفئات

INSERT INTO public.categories (name, name_ar, icon, color, sort_order, is_active) VALUES
('Old Project', 'المشروع القديم', 'history', '#FF9800', 1, true),
('Phase 1', 'المرحلة الأولى', 'play_arrow', '#2196F3', 2, true),
('Phase 2', 'المرحلة الثانية', 'trending_up', '#4CAF50', 3, true),
('Phase 3', 'المرحلة الثالثة', 'rocket_launch', '#9C27B0', 4, true),
('Inactive', 'غير نشط', 'pause_circle', '#F44336', 5, true);

-- 11) إدراج الوكلاء التجريبيين (مع reached_total)
-- ملاحظة: إذا لم يتم تحديد reached_total، سيتم استخدام active كقيمة افتراضية

INSERT INTO public.agents (name, note, contract_date, phase, site, fdt, board_name, phone, total_users, reached_total, active, prev_active) VALUES
-- المشروع القديم
('حسنين صاحب عبد', 'Said Al-shohdaa ITPC', '2024-09-01', 'OLD', 'موقع 1', '1-2-4-6-7', 'gsm', NULL, 2384, 1243, 1243, 1141),
('حسين عادل حسن', 'Said Al-shohdaa ITPC', '2024-09-01', 'OLD', 'موقع 2', '8', '12_IQCELL', NULL, 512, 241, 241, 271),
('سامر داخل سلمان', 'Said Al-shohdaa ITPC', '2024-09-01', 'OLD', 'موقع 3', '10_11', '11_IQCELL', NULL, 1024, 450, 450, 574),
('ضياء عبد الحسين', 'Said Al-shohdaa ITPC', '2024-09-01', 'OLD', 'موقع 4', '3_5_9', '10_IQCELL', NULL, 1536, 559, 559, 977),

-- المرحلة الثانية
('حسن حميد', 'Al-Mualmeen ITPC', '2024-12-26', 'PHASE2', 'موقع 5', '13,14', '25_IQCELL', NULL, 1280, 341, 341, 344),
('حسين علي عبد الامير', 'وكيل مرحلة 2', '2024-12-17', 'PHASE2', 'موقع 6', '21', '23_IQCELL', NULL, 640, 211, 211, 205),
('حسين علي عبد الامير', 'وكيل مرحلة 2', '2025-08-19', 'PHASE2', 'موقع 7', '10', '28_IQCELL', NULL, 640, 154, 154, 168),
('حيدرهاني', 'ABS ITPC', '2024-11-23', 'PHASE2', 'موقع 8', '11,12,16,17,18,19,1,2,13(1-23)', '19_IQCELL', NULL, 5488, 1626, 1626, 1617),
('زيد صالح', 'Al-Mualmeen ITPC', '2024-11-23', 'PHASE2', 'موقع 9', '15,16,17,18,19,22,23,24,25', '17_IQCELL', NULL, 5760, 1830, 1830, 1809),
('ضرغام باسم', 'Said Al-shohdaa ITPC', '2025-02-02', 'PHASE2', 'موقع 10', '22,31,32', '26_IQCELL', NULL, 1920, 976, 976, 968),
('عباس سعد حمزة', 'Said Al-shohdaa ITPC', '2024-09-01', 'PHASE2', 'موقع 11', '14_18_19', '-20IQCEEL', NULL, 1920, 821, 821, 815),
('علاء صاحب عبد علي', 'Al-Mualmeen ITPC', '2024-05-18', 'PHASE2', 'موقع 12', '20-21-22-27', 'IQCELL@2gsm_21', NULL, 2560, 1106, 1106, 1103),
('عيسى حسين', 'Al-Mualmeen ITPC', '2024-12-21', 'PHASE2', 'موقع 13', '29,30,31,32', '24_IQCELL', NULL, 2560, 1010, 1010, 1015),
('غيث علاء زكي', 'وكيل مرحلة 2', '2024-05-12', 'PHASE2', 'موقع 14', '15-16-17', 'ghaith', NULL, 1920, 866, 866, 868),
('فؤاد عايد', 'وكيل مرحلة 2', '2024-05-12', 'PHASE2', 'موقع 15', '12-13-30-29-28', '@fouad', NULL, 3200, 1408, 1408, 1402),
('محمد ابراهيم', 'Al-Mualmeen ITPC', '2024-11-23', 'PHASE2', 'موقع 16', '26,27,28,20', '16_IQCELL', NULL, 2560, 801, 801, 802),
('محمد ابراهيم', 'Al-Mualmeen ITPC', '2024-04-30', 'PHASE2', 'موقع 17', '1-8-9-2,14(14-40)', 'moh', NULL, 2352, 1219, 1219, 1215),
('محمد صاحب جابر', 'Saddle ITPC', '2024-05-05', 'PHASE2', 'موقع 18', '24-25-26-4-5', 'vlan', NULL, 3200, 1281, 1281, 1280),
('محمد عباس محمد', 'ABS ITPC', '2024-11-23', 'PHASE2', 'موقع 19', '3(1-18),10,14(21-24)', '18_IQCELL', NULL, 1088, 602, 602, 599),
('منتظر ماجد', 'ABS ITPC', '2024-11-23', 'PHASE2', 'موقع 20', '3(22-40),4,5,6,7,8,9,13(24-40),14(15-40),15', '15_IQCELL', NULL, 5488, 1697, 1697, 1689),
('منتظر ماجد', 'مجموعة مناطق', '2024-05-11', 'PHASE2', 'موقع 21', '3-7-6-2,13(1-13)', 'alnaqeeb', NULL, 2128, 1152, 1152, 1144),
('وليد علوي', 'Al-Mualmeen ITPC', '2024-12-28', 'PHASE2', 'موقع 22', '11,12', '22_IQCELL', NULL, 1280, 347, 347, 345),

-- المرحلة الثالثة
('حسنين صاحب', 'IQCELL_29', '2025-08-20', 'PHASE3', 'موقع 23', '33', '29_IQCELL', NULL, 640, 265, 265, 263),
('عراق سيل', 'وكيل مرحلة 3', '2025-09-16', 'PHASE3', 'موقع 24', '1-2-3-4-5-6-7-8-9', '30_IQCELL', NULL, 4880, 1292, 1292, 1297),
('عراق سيل', 'وكيل مرحلة 3', '2025-09-16', 'PHASE3', 'موقع 25', '9-10-11-12-13-14-15', '31_IQCELL', NULL, 4256, 200, 200, 92);

-- 12) التحقق من البيانات المدرجة

SELECT 
  'Users' as table_name,
  COUNT(*) as total_records,
  COUNT(CASE WHEN status = 'active' THEN 1 END) as active_records,
  COUNT(CASE WHEN role = 'admin' THEN 1 END) as admin_count
FROM public.users
UNION ALL
SELECT 
  'Agents' as table_name,
  COUNT(*) as total_records,
  COUNT(CASE WHEN phase = 'OLD' THEN 1 END) as old_agents,
  COUNT(CASE WHEN phase = 'PHASE2' THEN 1 END) as phase2_agents
FROM public.agents
UNION ALL
SELECT 
  'Categories' as table_name,
  COUNT(*) as total_records,
  COUNT(CASE WHEN is_active = true THEN 1 END) as active_records,
  0 as extra_count
FROM public.categories;

-- 13) عرض البيانات

SELECT 'Users Data:' as info;
SELECT id, username, full_name, role, status, created_at FROM public.users ORDER BY created_at;

SELECT 'Agents Data:' as info;
SELECT id, name, phase, total_users, reached_total, active, board_name FROM public.agents ORDER BY phase, name;

SELECT 'Categories Data:' as info;
SELECT id, name_ar, color, sort_order, is_active FROM public.categories ORDER BY sort_order;

